create table if not exists public.favorites(
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.users(id) on delete cascade,
    property_id bigint not null references public.properties(id) on delete cascade,
    created_at timestamp with time zone default now() not null,
    unique(user_id, property_id)
);