create table if not exists public.properties_types(
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamp with time zone default now() not null
);

create table if not exists public.provinces(
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamp with time zone default now() not null
);
create table if not exists public.roads(
    id bigint generated by default as identity primary key,
    road_name text not null unique,
    created_at timestamp with time zone default now() not null
);
create table if not exists public.users(
    id uuid primary key,
    user_id text not null unique,
    photo text,
    first_name text not null,
    last_name text not null,
    email text not null unique,
    phone text not null,
    vpoints integer default 0 not null,
    joined_at timestamp with time zone default now() not null
);

drop trigger if exists generate_user_id on public.users;
drop function if exists public.generate_user_id();
create or replace function public.generate_user_id() 
returns trigger as
$$  
    begin
        if new.user_id is null then
            new.user_id = concat(
                            to_char(CURRENT_DATE, 'YYYYMM'),
                            lpad((coalesce((SELECT count(1) FROM public.users), 0) + 1)::text, 4, '0')
                            );
        end if;
        return new;
    end; 
$$ language plpgsql;

create trigger generate_user_id
    before insert on public.users
    for each row
    execute procedure public.generate_user_id();

create table if not exists public.vpoint_transactions(
    id bigint generated by default as identity primary key,
    transaction_id text not null unique,
    type text not null,
    user_id uuid not null references public.users(id) on delete cascade,
    vpoints integer not null,
    created_at timestamp with time zone default now() not null
);

create or replace function public.generate_vpoint_transaction_id()
returns trigger as
$$
    begin
        if new.transaction_id is null then
            new.transaction_id = substring(md5(gen_random_uuid()::text) FROM 1 FOR 8);
        end if;
        return new;
    end; 
$$ language plpgsql;

drop trigger if exists generate_vpoint_transaction_id on public.vpoint_transactions;
create trigger generate_vpoint_transaction_id
    before insert on public.vpoint_transactions
    for each row
    execute procedure public.generate_vpoint_transaction_id();

create or replace function public.update_vpoints()
returns trigger as
$$ 
    declare
        _vpoints integer;
    begin
        update public.users set vpoints = vpoints + new.vpoints where id = new.user_id returning vpoints into _vpoints;
        
        if _vpoints < 0 then
            raise exception 'Insufficient vpoints';
        end if;

        return new;
    end; 
$$ language plpgsql;


drop trigger if exists update_vpoints on public.vpoint_transactions;
create trigger update_vpoints
    after insert on public.vpoint_transactions
    for each row
    execute procedure public.update_vpoints();


create or replace function public.on_auth_user_inserted()
returns trigger as
$$
    begin
        insert into public.users(id, photo, first_name, last_name, phone, email) values (
            new.id, 
            new.raw_user_meta_data->>'photo',
            new.raw_user_meta_data->>'first_name',
            new.raw_user_meta_data->>'last_name',
            new.raw_user_meta_data->>'phone',
            new.email
        );
        return new;
    end; 
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_inserted on auth.users;
create trigger on_auth_user_inserted
    after insert on auth.users
    for each row
    execute procedure public.on_auth_user_inserted();


create table if not exists public.properties(
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.users(id) on delete cascade,
    property_id text not null unique,
    listing_type text not null check (listing_type in ('sale', 'rent')),
    images text[] not null,
    title text not null,
    description text not null,
    latitude numeric not null,
    longitude numeric not null,
    property_type_id bigint not null references public.properties_types(id) on delete cascade,
    province_id bigint not null references public.provinces(id) on delete cascade,
    price numeric not null,
    sqm numeric not null,
    bedrooms integer,
    bathrooms integer,
    floors integer,
    parking integer,
    price_per_sqm numeric not null,
    living_rooms integer,
    land_length numeric not null,
    land_width numeric not null,
    building_length numeric not null,
    building_width numeric not null,
    created_at timestamp with time zone default now() not null
);

create table if not exists public.banks(
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamp with time zone default now() not null
);

create table if not exists public.auto_verbals(
    id bigint generated by default as identity primary key,
    auto_verbal_id text not null unique,
    image text not null,
    property_type_id bigint not null references public.properties_types(id) on delete cascade,
    bank_id bigint references public.banks(id) on delete set null,
    latitude numeric not null,
    longitude numeric not null,
    user_id uuid not null references public.users(id) on delete cascade,
    owner_name text not null,
    owner_phone text not null,
    bank_officer_name text,
    bank_officer_phone text,
    address text not null,
    created_at timestamp with time zone default now() not null
);

create or replace function public.create_vpoint_transaction_on_auto_verbal_inserted()
returns trigger as
$$
    begin
        insert into public.vpoint_transactions(type, user_id, vpoints) values (
            'auto_verbal',
            new.user_id,
            -new.price
        );
        return new;
    end; 
$$ language plpgsql;

drop trigger if exists create_vpoint_transaction_on_auto_verbal_inserted on public.auto_verbals;
create trigger create_vpoint_transaction_on_auto_verbal_inserted
    after insert on public.auto_verbals
    for each row
    execute procedure public.create_vpoint_transaction_on_auto_verbal_inserted();
