-- create table
--   public.auto_verbals (
--     id bigint generated by default as identity,
--     auto_verbal_id text not null,
--     image text not null,
--     property_type_id bigint not null,
--     bank_id bigint null,
--     latitude numeric not null,
--     longitude numeric not null,
--     user_id uuid not null,
--     owner_name text not null,
--     owner_phone text not null,
--     bank_officer_name text null,
--     bank_officer_phone text null,
--     address text null,
--     created_at timestamp with time zone not null default now(),
--     approved_at timestamp with time zone null,
--     approved_by uuid null,
--     reject_at timestamp with time zone null,
--     status text not null default 'pending'::text,
--     reject_reason text null,
--     province_id bigint null,
--     min_value numeric null,
--     max_value numeric null,
--     min_value_sqm numeric null,
--     max_value_sqm numeric null,
--     landwidth numeric null,
--     landlength numeric null,
--     area numeric null,
--     buildinglength numeric null,
--     buildingwidth numeric null,
--     bankbranch text null,
--     road_id bigint null,
--     bed numeric null,
--     bath numeric null,
--     livingroom numeric null,
--     floor numeric null,
--     constraint auto_verbals_pkey primary key (id),
--     constraint auto_verbals_auto_verbal_id_key unique (auto_verbal_id),
--     constraint auto_verbals_property_type_id_fkey foreign key (property_type_id) references properties_types (id) on delete cascade,
--     constraint auto_verbals_province_id_fkey foreign key (province_id) references provinces (id) on update cascade on delete cascade,
--     constraint auto_verbals_road_id_fkey foreign key (road_id) references roads (id) on update cascade on delete set null,
--     constraint auto_verbals_user_id_fkey foreign key (user_id) references users (id) on delete cascade,
--     constraint auto_verbals_approved_by_fkey foreign key (approved_by) references users (id) on delete set null,
--     constraint auto_verbals_user_id_fkey1 foreign key (user_id) references users (id) on update cascade on delete cascade,
--     constraint auto_verbals_bank_id_fkey foreign key (bank_id) references banks (id) on delete set null
--   ) tablespace pg_default;

-- create trigger create_vpoint_transaction_on_auto_verbal_inserted
-- after insert on auto_verbals for each row
-- execute function create_vpoint_transaction_on_auto_verbal_inserted ();

-- create trigger auto_generate_auto_verbal_id before insert on auto_verbals for each row
-- execute function generate_auto_verbal_id ();
-- Function to send notification when an auto verbal is approved or rejected
CREATE OR REPLACE FUNCTION notify_user_auto_verbal_status_change()
RETURNS TRIGGER AS $$
DECLARE
  auto_verbal_owner_id UUID;
  notification_message TEXT;
  notification_title TEXT;
BEGIN
  -- Get the user ID of the auto verbal owner
  SELECT user_id INTO auto_verbal_owner_id
  FROM public.auto_verbals
  WHERE id = NEW.id;
  -- Prepare notification message and title based on the status change
  IF NEW.status = 'approved' THEN
    notification_title := 'Auto Verbal Approved';
    notification_message := format('Your auto verbal (ID: %s) has been approved. The minimum price has been set to %s and the maximum price to %s.', NEW.auto_verbal_id, NEW.min_value, NEW.max_value);
  ELSIF NEW.status = 'rejected' THEN
    notification_title := 'Auto Verbal Rejected';
    notification_message := format('Your auto verbal (ID: %s) has been rejected.', NEW.auto_verbal_id);
  ELSE
    -- If the status is neither approved nor rejected, don't send a notification
    RETURN NEW;
  END IF;

  -- Send notification to the auto verbal owner
  PERFORM send_onesignal_notification(
    notification_message,
    notification_title,
    ARRAY[auto_verbal_owner_id]
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for auto verbal status changes
DROP TRIGGER IF EXISTS auto_verbal_status_change_notification ON public.auto_verbals;
CREATE TRIGGER auto_verbal_status_change_notification
AFTER UPDATE OF status ON public.auto_verbals
FOR EACH ROW
WHEN (OLD.status IS DISTINCT FROM NEW.status)
EXECUTE FUNCTION notify_user_auto_verbal_status_change();

-- Function to send notification to admin when a new auto verbal is added
CREATE OR REPLACE FUNCTION notify_admin_new_auto_verbal()
RETURNS TRIGGER AS $$
DECLARE
  admin_user_ids UUID[];
  notification_message TEXT;
  notification_title TEXT;
BEGIN
  -- Get all admin user IDs
  SELECT ARRAY_AGG(id) INTO admin_user_ids
  FROM public.users
  WHERE is_admin = true;

  -- Prepare notification message and title
  notification_title := 'New Auto Verbal Added';
  notification_message := format('A new auto verbal (ID: %s) has been added and is pending approval.', NEW.auto_verbal_id);

  -- Send notification to all admins
  PERFORM send_onesignal_notification(
    notification_message,
    notification_title,
    admin_user_ids
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for new auto verbal notifications
DROP TRIGGER IF EXISTS new_auto_verbal_notification ON public.auto_verbals;
CREATE TRIGGER new_auto_verbal_notification
AFTER INSERT ON public.auto_verbals
FOR EACH ROW
EXECUTE FUNCTION notify_admin_new_auto_verbal();
