create table if not exists public.notifications(
    id bigint generated by default as identity primary key,
    title text not null,
    message text not null,
    user_id uuid not null
);

-- Tigger to [func_notifications_send] on [notifications] table ---------------------------------------------
create or replace function public.func_notifications_send()
returns trigger as
$$
    begin
        -- Send notification using OneSignal
        perform send_onesignal_notification(
            new.message,
            new.title,
            ARRAY[new.user_id]
        );
        return coalesce(new, old);
    end; 
$$ language plpgsql;

-- Drop existed trigger, to ensure new will be update
drop trigger if exists tr_notifications_send on public.notifications;
create trigger tr_notifications_send
    after insert
    on public.notifications
for each row execute procedure public.func_notifications_send();



-- Function to send notification to admin when an auto verbal is resubmitted
CREATE OR REPLACE FUNCTION notify_admin_auto_verbal_resubmitted()
RETURNS TRIGGER AS $$
DECLARE
  admin_user_ids UUID[];
  notification_message TEXT;
  notification_title TEXT;
BEGIN
  -- Only proceed if the new status is 'resubmit'
  IF NEW.status = 'resubmit' THEN
    -- Get all admin user IDs
    SELECT ARRAY_AGG(id) INTO admin_user_ids
    FROM public.users
    WHERE is_admin = true;

    -- Prepare notification message and title
    notification_title := 'Auto Verbal Resubmitted';
    notification_message := format('Auto verbal (ID: %s) has been resubmitted and requires review.', NEW.auto_verbal_id);

    -- Insert notification record for each admin
    FOR admin_id IN SELECT unnest(admin_user_ids) LOOP
      INSERT INTO public.notifications (title, message, user_id)
      VALUES (notification_title, notification_message, admin_id);
    END LOOP;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;



-- Function to send notification to admin when a new auto verbal is added
CREATE OR REPLACE FUNCTION notify_admin_new_auto_verbal()
RETURNS TRIGGER AS $$
DECLARE
  admin_user_ids UUID[];
  notification_message TEXT;
  notification_title TEXT;
BEGIN
  -- Get all admin user IDs
  SELECT ARRAY_AGG(id) INTO admin_user_ids
  FROM public.users
  WHERE is_admin = true;

  -- Prepare notification message and title
  notification_title := 'New Auto Verbal Added';
  notification_message := format('A new auto verbal (ID: %s) has been added and is pending approval.', NEW.auto_verbal_id);

  -- Insert notification record for each admin
  FOR admin_id IN SELECT unnest(admin_user_ids) LOOP
    INSERT INTO public.notifications (title, message, user_id)
    VALUES (notification_title, notification_message, admin_id);
  END LOOP;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;



-- Trigger function to send notification when a new property is created
CREATE OR REPLACE FUNCTION notify_admins_new_property()
RETURNS TRIGGER AS $$

DECLARE
  admin_ids UUID[];
  property_info TEXT;
BEGIN
  -- Get admin user IDs
  admin_ids := get_admin_user_ids();
  
  -- Prepare property information
  property_info := format(
    'New property created: %s (ID: %s) - %s in %s. Price: $%s, Area: %s sqm',
    NEW.title,
    NEW.property_id,
    (SELECT name FROM public.properties_types WHERE id = NEW.property_type_id),
    (SELECT name FROM public.provinces WHERE id = NEW.province_id),
    NEW.price::text,
    NEW.sqm::text
  );
  
  -- Insert notification record for each admin
  FOR admin_id IN SELECT unnest(admin_ids) LOOP
    INSERT INTO public.notifications (title, message, user_id)
    VALUES ('New Property Alert', property_info, admin_id);
  END LOOP;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


