create table if not exists public.property_likes(
    id bigint generated by default as identity primary key,
    property_id bigint not null references public.properties(id) on delete cascade,
    user_id uuid not null references public.users(id) on delete cascade,
    created_at timestamp with time zone default now() not null,
    unique(property_id, user_id)
);

create table if not exists public.property_comments(
    id bigint generated by default as identity primary key,
    property_id bigint not null references public.properties(id) on delete cascade,
    user_id uuid not null references public.users(id) on delete cascade,
    created_at timestamp with time zone default now() not null,
    content text not null,
    unique(property_id, user_id)
);

-- Drop unique constraint on property_comments table
alter table public.property_comments
drop constraint if exists property_comments_property_id_user_id_key;


create or replace function public.increment_property_view_count(property_id bigint)
returns void as
$$
    begin
        update public.properties
        set view_count = view_count + 1
        where id = $1;
    end; 
$$ language plpgsql;