import 'package:freezed_annotation/freezed_annotation.dart';

part 'auto_verbal_model.freezed.dart';
part 'auto_verbal_model.g.dart';

@freezed
class AutoVerbalModel with _$AutoVerbalModel {
  factory AutoVerbalModel({
    required int id,
    required String autoVerbalId,
    required String image,
    required int propertyTypeId,
    required int? bankid,
    required double latitude,
    required double longitude,
    required String userId,
    required String ownerName,
    required String ownerPhone,
    required String? bankOfficerName,
    required String? bankOfficerPhone,
    required String address,
    required DateTime createdAt,
  }) = _AutoVerbalModel;

  factory AutoVerbalModel.fromJson(Map<String, dynamic> json) =>
      _$AutoVerbalModelFromJson(json);
}


/*

create table if not exists public.auto_verbals(
    id bigint generated by default as identity primary key,
    autoVerbalId text not null unique,
    image text not null,
    propertyTypeId bigint not null references public.properties_type(id)  on delete cascade,
    bankId bigint references public.banks(id) on delete set null,
    latitude numeric not null,
    longitude numeric not null,
    userId uuid not null references public.users(id) on delete cascade,
    ownerName text not null,
    ownerPhone text not null,
    bankOfficerName text,
    bankOfficerPhone text,
    address text not null,
    createdAt timestamp with time zone default now() not null
);
 */