import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:kfa_mobile_nu/exports.dart';
import 'package:kfa_mobile_nu/src/models/user_model.dart';

part 'auto_verbal_model.freezed.dart';
part 'auto_verbal_model.g.dart';

@freezed
class AutoVerbalModel with _$AutoVerbalModel {
  const AutoVerbalModel._();
  @TableModel('auto_verbals')
  factory AutoVerbalModel({
    @JsonKey(name: 'id') required int id,
    @JsonKey(name: 'auto_verbal_id') required String autoVerbalId,
    @JsonKey(name: 'image') required String image,
    @JsonKey(name: 'property_type_id') required int propertyTypeId,
    @JsonKey(name: 'bank_id') required int? bankid,
    @JsonKey(name: 'latitude') required double latitude,
    @JsonKey(name: 'longitude') required double longitude,
    @JsonKey(name: 'owner_name') required String ownerName,
    @JsonKey(name: 'owner_phone') required String ownerPhone,
    @JsonKey(name: 'bank_officer_name') required String? bankOfficerName,
    @JsonKey(name: 'bank_officer_phone') required String? bankOfficerPhone,
    @JsonKey(name: 'address') required String address,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    @JsonKey(name: 'approved_at') required DateTime approvedAt,
    @JsonKey(name: 'reject_at') required DateTime? rejectedAt,
    @JsonKey(name: 'status') required String? status,
    @JsonKey(name: 'reject_reason') required String? rejectReason,
    @JoinedColumn(foreignKey: 'user_id') required UserModel user,
    @JoinedColumn(foreignKey: 'approved_by') required UserModel approvedBy,
  }) = _AutoVerbalModel;

  factory AutoVerbalModel.fromJson(Map<String, dynamic> json) =>
      _$AutoVerbalModelFromJson(json);

  static const TableBuilder table = _tableAutoVerbalModel;
}

/*
create table if not exists public.auto_verbals(
    id bigint generated by default as identity primary key,
    autoVerbalId text not null unique,
    image text not null,
    propertyTypeId bigint not null references public.properties_type(id)  on delete cascade,
    bankId bigint references public.banks(id) on delete set null,
    latitude numeric not null,
    longitude numeric not null,
    userId uuid not null references public.users(id) on delete cascade,
    ownerName text not null,
    ownerPhone text not null,
    bankOfficerName text,
    bankOfficerPhone text,
    address text not null,
    createdAt timestamp with time zone default now() not null
);
 */