// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// KimappSchemaGenerator
// **************************************************************************

// ignore_for_file: invalid_annotation_target, unused_import
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:kimapp/kimapp.dart';

import 'package:kfa_mobile_nu/exports.dart';
import 'package:kfa_mobile_nu/src/models/property_model.schema.dart';
import 'package:kfa_mobile_nu/src/models/user_model.dart';
import 'favorit_model.dart';

part 'favorit_model.schema.freezed.dart';
part 'favorit_model.schema.g.dart';

/// Defines the table structure for Favorite.
/// This class provides constant string values for table and column names,
/// facilitating type-safe database operations and query building.
class FavoriteTable {
  const FavoriteTable._();

  /// The name of the database table for Favorite entities.
  /// Use this constant for constructing SQL queries to ensure consistency.
  static const String table = "favorite";

  /// Column: id
  /// Data type: `int`
  /// Key: `id`
  static const String id = "id";

  /// Column: user_id
  /// Data type: `String`
  /// Key: `user_id`
  static const String userId = "user_id";

  /// Column: property_id
  /// Data type: `String`
  /// Key: `property_id`
  static const String propertyId = "property_id";

  /// Column: created_at
  /// Data type: `DateTime`
  /// Key: `created_at`
  static const String createdAt = "created_at";

  /// Column: user_id
  /// This is a join key for field user.
  /// Data type: `UserModel`
  /// Key: `user`
  static const String user = "user";

  /// Column: property_id
  /// This is a join key for field property.
  /// Data type: `PropertyModel`
  /// Key: `property`
  static const String property = "property";
}

/// Base model class for FavoriteModel.
@freezed
class FavoriteModel with _$FavoriteModel {
  const FavoriteModel._();

  /// Table name: `favorite`
  static const String tableName = "favorite";

  /// Field name for id field with JsonKey('id')
  static const String idKey = "id";

  /// Field name for userId field with JsonKey('user_id')
  static const String userIdKey = "user_id";

  /// Field name for propertyId field with JsonKey('property_id')
  static const String propertyIdKey = "property_id";

  /// Field name for createdAt field with JsonKey('created_at')
  static const String createdAtKey = "created_at";

  /// Field name for user field with JsonKey('user')
  /// This is json key for joined field. with foreign key: user_id and candidate key: null
  static const String userKey = "user";

  /// Field name for property field with JsonKey('property')
  /// This is json key for joined field. with foreign key: property_id and candidate key: null
  static const String propertyKey = "property";

  /// Constructor for FavoriteModel.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `enabled` (`favorite`)
  ///
  /// Fields:
  /// - int id : JsonKey('id')
  /// - String userId : JsonKey('user_id')
  /// - String propertyId : JsonKey('property_id')
  /// - DateTime createdAt : JsonKey('created_at')
  /// - UserModel user : JsonKey('user')
  /// - PropertyModel property : JsonKey('property')
  @TableModel(FavoriteModel.tableName)
  const factory FavoriteModel({
    @JsonKey(name: FavoriteModel.idKey) required int id,
    @JsonKey(name: FavoriteModel.userIdKey) required String userId,
    @JsonKey(name: FavoriteModel.propertyIdKey) required String propertyId,
    @JsonKey(name: FavoriteModel.createdAtKey) required DateTime createdAt,
    @JoinedColumn(foreignKey: "user_id", candidateKey: null)
    @JsonKey(name: FavoriteModel.userKey)
    required UserModel user,
    @JoinedColumn(foreignKey: "property_id", candidateKey: null)
    @JsonKey(name: FavoriteModel.propertyKey)
    required PropertyModel property,
  }) = _FavoriteModel;

  /// Creates an instance of FavoriteModel from a JSON map.
  factory FavoriteModel.fromJson(Map<String, dynamic> json) =>
      _$FavoriteModelFromJson(json);

  /// Supabase table configuration for this model.
  static const TableBuilder table = _tableFavoriteModel;
}

/// Represents the CreateFavoriteParam model. generated by kimapp_generator
@freezed
class CreateFavoriteParam with _$CreateFavoriteParam {
  const CreateFavoriteParam._();

  /// Field name for userId field with JsonKey('user_id')
  static const String userIdKey = "user_id";

  /// Field name for propertyId field with JsonKey('property_id')
  static const String propertyIdKey = "property_id";

  /// Constructor for CreateFavoriteParam.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `disabled`
  ///
  /// Fields:
  /// - String userId : JsonKey('user_id')
  /// - String propertyId : JsonKey('property_id')
  const factory CreateFavoriteParam({
    @JsonKey(name: CreateFavoriteParam.userIdKey) required String userId,
    @JsonKey(name: CreateFavoriteParam.propertyIdKey)
    required String propertyId,
  }) = _CreateFavoriteParam;

  /// Creates an instance of CreateFavoriteParam from a JSON map.
  factory CreateFavoriteParam.fromJson(Map<String, dynamic> json) =>
      _$CreateFavoriteParamFromJson(json);
}

/// Represents the UpdateFavoriteParam model. generated by kimapp_generator
@freezed
class UpdateFavoriteParam with _$UpdateFavoriteParam {
  const UpdateFavoriteParam._();

  /// Field name for userId field with JsonKey('user_id')
  static const String userIdKey = "user_id";

  /// Field name for propertyId field with JsonKey('property_id')
  static const String propertyIdKey = "property_id";

  /// Constructor for UpdateFavoriteParam.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `disabled`
  ///
  /// Fields:
  /// - String userId : JsonKey('user_id')
  /// - String propertyId : JsonKey('property_id')
  const factory UpdateFavoriteParam({
    @JsonKey(name: UpdateFavoriteParam.userIdKey) required String userId,
    @JsonKey(name: UpdateFavoriteParam.propertyIdKey)
    required String propertyId,
  }) = _UpdateFavoriteParam;

  /// Creates an instance of UpdateFavoriteParam from a JSON map.
  factory UpdateFavoriteParam.fromJson(Map<String, dynamic> json) =>
      _$UpdateFavoriteParamFromJson(json);
}
