// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// KimappSchemaGenerator
// **************************************************************************

// ignore_for_file: invalid_annotation_target, unused_import
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:kimapp/kimapp.dart';

import 'package:kfa_mobile_nu/src/models/user_model.dart';
import 'property_comment_model.dart';

part 'property_comment_model.schema.freezed.dart';
part 'property_comment_model.schema.g.dart';

/// Defines the table structure for PropertyComment.
/// This class provides constant string values for table and column names,
/// facilitating type-safe database operations and query building.
class PropertyCommentTable {
  const PropertyCommentTable._();

  /// The name of the database table for PropertyComment entities.
  /// Use this constant for constructing SQL queries to ensure consistency.
  static const String table = "property_comments";

  /// Column: id
  /// This is the primary key column for the PropertyComment table.
  /// Data type: `int`
  /// Key: `id`
  static const String id = "id";

  /// Column: property_id
  /// Data type: `int`
  /// Key: `property_id`
  static const String propertyId = "property_id";

  /// Column: user_id
  /// Data type: `String`
  /// Key: `user_id`
  static const String userId = "user_id";

  /// Column: created_at
  /// Data type: `DateTime`
  /// Key: `created_at`
  static const String createdAt = "created_at";

  /// Column: content
  /// Data type: `String`
  /// Key: `content`
  static const String content = "content";

  /// Column: user_id
  /// This is a join key for field user.
  /// Data type: `UserModel`
  /// Key: `user`
  static const String user = "user";
}

/// Represents the unique identifier for a PropertyComment.
/// This class wraps the `int` value, providing type safety and encapsulation.
class PropertyCommentId extends Identity<int> {
  const PropertyCommentId._(this.value);

  @override
  final int value;

  /// Creates an instance of PropertyCommentId from a JSON value.
  /// Accepts int representations.
  /// Throws ArgumentError if the value is null or not of type int.
  factory PropertyCommentId.fromJson(dynamic value) {
    if (value is int) {
      return PropertyCommentId._(value);
    } else if (value == null) {
      throw ArgumentError.notNull('value');
    } else {
      throw ArgumentError(
          'Value of PropertyCommentId must be of type int, but was ${value.runtimeType}. Please provide the correct type.');
    }
  }

  /// Creates an instance of PropertyCommentId from a int value.
  factory PropertyCommentId.fromValue(int value) {
    return PropertyCommentId._(value);
  }
}

/// Base model class for PropertyCommentModel.
@freezed
class PropertyCommentModel with _$PropertyCommentModel {
  const PropertyCommentModel._();

  /// Table name: `property_comments`
  static const String tableName = "property_comments";

  /// Field name for id field with JsonKey('id')
  static const String idKey = "id";

  /// Field name for propertyId field with JsonKey('property_id')
  static const String propertyIdKey = "property_id";

  /// Field name for userId field with JsonKey('user_id')
  static const String userIdKey = "user_id";

  /// Field name for createdAt field with JsonKey('created_at')
  static const String createdAtKey = "created_at";

  /// Field name for content field with JsonKey('content')
  static const String contentKey = "content";

  /// Field name for user field with JsonKey('user')
  /// This is json key for joined field. with foreign key: user_id and candidate key: null
  static const String userKey = "user";

  /// Constructor for PropertyCommentModel.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `enabled` (`property_comments`)
  ///
  /// Fields:
  /// - PropertyCommentId id : JsonKey('id')
  /// - int propertyId : JsonKey('property_id')
  /// - String userId : JsonKey('user_id')
  /// - DateTime createdAt : JsonKey('created_at')
  /// - String content : JsonKey('content')
  /// - UserModel user : JsonKey('user')
  @TableModel(PropertyCommentModel.tableName)
  const factory PropertyCommentModel({
    @JsonKey(name: PropertyCommentModel.idKey) required PropertyCommentId id,
    @JsonKey(name: PropertyCommentModel.propertyIdKey) required int propertyId,
    @JsonKey(name: PropertyCommentModel.userIdKey) required String userId,
    @JsonKey(name: PropertyCommentModel.createdAtKey)
    required DateTime createdAt,
    @JsonKey(name: PropertyCommentModel.contentKey) required String content,
    @JoinedColumn(foreignKey: "user_id", candidateKey: null)
    @JsonKey(name: PropertyCommentModel.userKey)
    required UserModel user,
  }) = _PropertyCommentModel;

  /// Creates an instance of PropertyCommentModel from a JSON map.
  factory PropertyCommentModel.fromJson(Map<String, dynamic> json) =>
      _$PropertyCommentModelFromJson(json);

  /// Supabase table configuration for this model.
  static const TableBuilder table = _tablePropertyCommentModel;
}
