// dart format width=80
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// KimappSchemaGenerator
// **************************************************************************

// ignore_for_file: invalid_annotation_target, unused_import, require_trailing_commas
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:kimapp/kimapp.dart';

import 'property_category_model.dart';

part 'property_category_model.schema.freezed.dart';
part 'property_category_model.schema.g.dart';

/// Defines the table structure for PropertyCategory.
/// This class provides constant string values for table and column names,
/// facilitating type-safe database operations and query building.
class PropertyCategoryTable {
  const PropertyCategoryTable._();

  /// The name of the database table for PropertyCategory entities.
  /// Use this constant for constructing SQL queries to ensure consistency.
  static const String table = "property_type_categories";

  /// Column: property_type_category_id
  /// Data type: `int`
  /// Key: `property_type_category_id`
  static const String id = "property_type_category_id";

  /// Column: category_name
  /// Data type: `String`
  /// Key: `category_name`
  static const String name = "category_name";

  /// Column: sale_count
  /// Data type: `int?`
  /// Key: `sale_count`
  static const String totalSale = "sale_count";

  /// Column: rent_count
  /// Data type: `int?`
  /// Key: `rent_count`
  static const String totalRent = "rent_count";
}

/// Base class of this schema, this is the parent of all generated models in this schema
abstract class BasePropertyCategorySchema {}

/// Base model class for this schema, this includes all properties of the base model, and get inherited by all generated models in this schema where [inheritAllFromBase()] is called and without any excepted fields.
abstract class IPropertyCategoryModel {
  int get id;
  String get name;
  int? get totalSale;
  int? get totalRent;
}

/// Base model class for PropertyCategoryModel.
@freezed
sealed class PropertyCategoryModel
    with _$PropertyCategoryModel
    implements BasePropertyCategorySchema, IPropertyCategoryModel {
  const PropertyCategoryModel._();

  /// Constructor for PropertyCategoryModel.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `enabled` (`property_type_categories`)
  ///
  /// Fields:
  /// - int id : JsonKey('property_type_category_id')
  /// - String name : JsonKey('category_name')
  /// - int? totalSale : JsonKey('sale_count')
  /// - int? totalRent : JsonKey('rent_count')
  @TableModel(PropertyCategoryModel.tableName)
  @JsonSerializable(explicitToJson: true)
  const factory PropertyCategoryModel({
    @JsonKey(name: PropertyCategoryModel.idKey) required int id,
    @JsonKey(name: PropertyCategoryModel.nameKey) required String name,
    @JsonKey(name: PropertyCategoryModel.totalSaleKey) required int? totalSale,
    @JsonKey(name: PropertyCategoryModel.totalRentKey) required int? totalRent,
  }) = _PropertyCategoryModel;

  /// Creates an instance of PropertyCategoryModel from a JSON map.
  factory PropertyCategoryModel.fromJson(Map<String, dynamic> json) =>
      _$PropertyCategoryModelFromJson(json);

  /// Supabase table configuration for this model.
  static const TableBuilder table = _tablePropertyCategoryModel;

  /// Table name: `property_type_categories`
  static const String tableName = "property_type_categories";

  /// Field name for id field with JsonKey('property_type_category_id')
  static const String idKey = "property_type_category_id";

  /// Field name for name field with JsonKey('category_name')
  static const String nameKey = "category_name";

  /// Field name for totalSale field with JsonKey('sale_count')
  static const String totalSaleKey = "sale_count";

  /// Field name for totalRent field with JsonKey('rent_count')
  static const String totalRentKey = "rent_count";
}
