// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// KimappSchemaGenerator
// **************************************************************************

// ignore_for_file: invalid_annotation_target, unused_import, require_trailing_commas
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:kimapp/kimapp.dart';

import 'package:kfa_mobile_nu/src/models/user_model.dart';
import 'property_like_model.dart';

part 'property_like_model.schema.freezed.dart';
part 'property_like_model.schema.g.dart';

/// Defines the table structure for PropertyLike.
/// This class provides constant string values for table and column names,
/// facilitating type-safe database operations and query building.
class PropertyLikeTable {
  const PropertyLikeTable._();

  /// The name of the database table for PropertyLike entities.
  /// Use this constant for constructing SQL queries to ensure consistency.
  static const String table = "property_likes";

  /// Column: id
  /// This is the primary key column for the PropertyLike table.
  /// Data type: `int`
  /// Key: `id`
  static const String id = "id";

  /// Column: property_id
  /// Data type: `String`
  /// Key: `property_id`
  static const String propertyId = "property_id";

  /// Column: user_id
  /// Data type: `String`
  /// Key: `user_id`
  static const String userId = "user_id";

  /// Column: created_at
  /// Data type: `DateTime`
  /// Key: `created_at`
  static const String createdAt = "created_at";

  /// Column: user_id
  /// This is a join key for field user.
  /// Data type: `UserModel`
  /// Key: `user`
  static const String user = "user";
}

/// Represents the unique identifier for a PropertyLike.
/// This class wraps the `int` value, providing type safety and encapsulation.
class PropertyViewId extends Identity<int> {
  const PropertyViewId._(this.value);

  @override
  final int value;

  /// Creates an instance of PropertyViewId from a JSON value.
  /// Accepts int representations.
  /// Throws ArgumentError if the value is null or not of type int.
  factory PropertyViewId.fromJson(dynamic value) {
    if (value is int) {
      return PropertyViewId._(value);
    } else if (value == null) {
      throw ArgumentError.notNull('value');
    } else {
      throw ArgumentError(
          'Value of PropertyViewId must be of type int, but was ${value.runtimeType}. Please provide the correct type.');
    }
  }

  /// Creates an instance of PropertyViewId from a int value.
  factory PropertyViewId.fromValue(int value) {
    return PropertyViewId._(value);
  }
}

/// Base model class for PropertyLikeModel.
@freezed
class PropertyLikeModel with _$PropertyLikeModel {
  const PropertyLikeModel._();

  /// Constructor for PropertyLikeModel.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `enabled` (`property_likes`)
  ///
  /// Fields:
  /// - PropertyViewId id : JsonKey('id')
  /// - String propertyId : JsonKey('property_id')
  /// - String userId : JsonKey('user_id')
  /// - DateTime createdAt : JsonKey('created_at')
  /// - UserModel user : JsonKey('user')
  @TableModel(PropertyLikeModel.tableName)
  @JsonSerializable(explicitToJson: true)
  const factory PropertyLikeModel({
    @JsonKey(name: PropertyLikeModel.idKey) required PropertyViewId id,
    @JsonKey(name: PropertyLikeModel.propertyIdKey) required String propertyId,
    @JsonKey(name: PropertyLikeModel.userIdKey) required String userId,
    @JsonKey(name: PropertyLikeModel.createdAtKey) required DateTime createdAt,
    @JoinedColumn(foreignKey: "user_id", candidateKey: null)
    @JsonKey(name: PropertyLikeModel.userKey)
    required UserModel user,
  }) = _PropertyLikeModel;

  /// Creates an instance of PropertyLikeModel from a JSON map.
  factory PropertyLikeModel.fromJson(Map<String, dynamic> json) =>
      _$PropertyLikeModelFromJson(json);

  /// Supabase table configuration for this model.
  static const TableBuilder table = _tablePropertyLikeModel;

  /// Table name: `property_likes`
  static const String tableName = "property_likes";

  /// Field name for id field with JsonKey('id')
  static const String idKey = "id";

  /// Field name for propertyId field with JsonKey('property_id')
  static const String propertyIdKey = "property_id";

  /// Field name for userId field with JsonKey('user_id')
  static const String userIdKey = "user_id";

  /// Field name for createdAt field with JsonKey('created_at')
  static const String createdAtKey = "created_at";

  /// Field name for user field with JsonKey('user')
  /// This is json key for joined field. with foreign key: user_id and candidate key: null
  static const String userKey = "user";
}
