// dart format width=80
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// KimappSchemaGenerator
// **************************************************************************

// ignore_for_file: invalid_annotation_target, unused_import, require_trailing_commas
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:kimapp/kimapp.dart';

import 'package:kfa_mobile_nu/exports.dart';
import 'property_type_model.dart';

part 'property_type_model.schema.freezed.dart';
part 'property_type_model.schema.g.dart';

/// Defines the table structure for PropertyType.
/// This class provides constant string values for table and column names,
/// facilitating type-safe database operations and query building.
class PropertyTypeTable {
  const PropertyTypeTable._();

  /// The name of the database table for PropertyType entities.
  /// Use this constant for constructing SQL queries to ensure consistency.
  static const String table = "properties_types";

  /// Column: id
  /// Data type: `int`
  /// Key: `id`
  static const String id = "id";

  /// Column: name
  /// Data type: `String`
  /// Key: `name`
  static const String name = "name";
}

/// Base class of this schema, this is the parent of all generated models in this schema
abstract class BasePropertyTypeSchema {}

/// Base model class for this schema, this includes all properties of the base model, and get inherited by all generated models in this schema where [inheritAllFromBase()] is called and without any excepted fields.
abstract class IPropertyTypeModel {
  int get id;
  String get name;
}

/// Base model class for PropertyTypeModel.
@freezed
sealed class PropertyTypeModel
    with _$PropertyTypeModel
    implements BasePropertyTypeSchema, IPropertyTypeModel {
  const PropertyTypeModel._();

  /// Constructor for PropertyTypeModel.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `enabled` (`properties_types`)
  ///
  /// Fields:
  /// - int id : JsonKey('id')
  /// - String name : JsonKey('name')
  @TableModel(PropertyTypeModel.tableName)
  @JsonSerializable(explicitToJson: true)
  const factory PropertyTypeModel({
    @JsonKey(name: PropertyTypeModel.idKey) required int id,
    @JsonKey(name: PropertyTypeModel.nameKey) required String name,
  }) = _PropertyTypeModel;

  /// Creates an instance of PropertyTypeModel from a JSON map.
  factory PropertyTypeModel.fromJson(Map<String, dynamic> json) =>
      _$PropertyTypeModelFromJson(json);

  /// Supabase table configuration for this model.
  static const TableBuilder table = _tablePropertyTypeModel;

  /// Table name: `properties_types`
  static const String tableName = "properties_types";

  /// Field name for id field with JsonKey('id')
  static const String idKey = "id";

  /// Field name for name field with JsonKey('name')
  static const String nameKey = "name";
}
