// dart format width=80
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// KimappSchemaGenerator
// **************************************************************************

// ignore_for_file: invalid_annotation_target, unused_import, require_trailing_commas
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:kimapp/kimapp.dart';

import 'package:kfa_mobile_nu/exports.dart';
import 'province_model.dart';

part 'province_model.schema.freezed.dart';
part 'province_model.schema.g.dart';

/// Defines the table structure for Province.
/// This class provides constant string values for table and column names,
/// facilitating type-safe database operations and query building.
class ProvinceTable {
  const ProvinceTable._();

  /// The name of the database table for Province entities.
  /// Use this constant for constructing SQL queries to ensure consistency.
  static const String table = "provinces";

  /// Column: id
  /// Data type: `int`
  /// Key: `id`
  static const String id = "id";

  /// Column: name
  /// Data type: `String`
  /// Key: `name`
  static const String name = "name";
}

/// Base class of this schema, this is the parent of all generated models in this schema
abstract class BaseProvinceSchema {}

/// Base model class for this schema, this includes all properties of the base model, and get inherited by all generated models in this schema where [inheritAllFromBase()] is called and without any excepted fields.
abstract class IProvinceModel {
  int get id;
  String get name;
}

/// Base model class for ProvinceModel.
@freezed
sealed class ProvinceModel
    with _$ProvinceModel
    implements BaseProvinceSchema, IProvinceModel {
  const ProvinceModel._();

  /// Constructor for ProvinceModel.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `enabled` (`provinces`)
  ///
  /// Fields:
  /// - int id : JsonKey('id')
  /// - String name : JsonKey('name')
  @TableModel(ProvinceModel.tableName)
  @JsonSerializable(explicitToJson: true)
  const factory ProvinceModel({
    @JsonKey(name: ProvinceModel.idKey) required int id,
    @JsonKey(name: ProvinceModel.nameKey) required String name,
  }) = _ProvinceModel;

  /// Creates an instance of ProvinceModel from a JSON map.
  factory ProvinceModel.fromJson(Map<String, dynamic> json) =>
      _$ProvinceModelFromJson(json);

  /// Supabase table configuration for this model.
  static const TableBuilder table = _tableProvinceModel;

  /// Table name: `provinces`
  static const String tableName = "provinces";

  /// Field name for id field with JsonKey('id')
  static const String idKey = "id";

  /// Field name for name field with JsonKey('name')
  static const String nameKey = "name";
}
