// dart format width=80
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// KimappSchemaGenerator
// **************************************************************************

// ignore_for_file: invalid_annotation_target, unused_import, require_trailing_commas
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:kimapp/kimapp.dart';

import 'package:kfa_mobile_nu/exports.dart';
import 'user_model.dart';

part 'user_model.schema.freezed.dart';
part 'user_model.schema.g.dart';

/// Defines the table structure for User.
/// This class provides constant string values for table and column names,
/// facilitating type-safe database operations and query building.
class UserTable {
  const UserTable._();

  /// The name of the database table for User entities.
  /// Use this constant for constructing SQL queries to ensure consistency.
  static const String table = "users";

  /// Column: id
  /// Data type: `String`
  /// Key: `id`
  static const String id = "id";

  /// Column: user_id
  /// Data type: `String`
  /// Key: `user_id`
  static const String userId = "user_id";

  /// Column: photo
  /// Data type: `String?`
  /// Key: `photo`
  static const String photo = "photo";

  /// Column: first_name
  /// Data type: `String?`
  /// Key: `first_name`
  static const String rawFirstName = "first_name";

  /// Column: last_name
  /// Data type: `String?`
  /// Key: `last_name`
  static const String rawLastName = "last_name";

  /// Column: email
  /// Data type: `String`
  /// Key: `email`
  static const String email = "email";

  /// Column: phone
  /// Data type: `String?`
  /// Key: `phone`
  static const String rawPhone = "phone";

  /// Column: vpoints
  /// Data type: `int`
  /// Key: `vpoints`
  static const String vpoints = "vpoints";

  /// Column: role
  /// Data type: `UserRole`
  /// Key: `role`
  static const String role = "role";

  /// Column: joined_at
  /// Data type: `DateTime`
  /// Key: `joined_at`
  static const String joinedAt = "joined_at";

  /// Column: active
  /// Data type: `bool`
  /// Key: `active`
  static const String active = "active";

  /// Column: managed_by_id
  /// This is a join key for field managedBy.
  /// Data type: `UserLiteModel?`
  /// Key: `managedBy`
  static const String managedBy = "managedBy";
}

/// Base class of this schema, this is the parent of all generated models in this schema
abstract class BaseUserSchema {}

/// Base model class for this schema, this includes all properties of the base model, and get inherited by all generated models in this schema where [inheritAllFromBase()] is called and without any excepted fields.
abstract class IUserModel {
  String get id;
  String get userId;
  String? get photo;
  String? get rawFirstName;
  String? get rawLastName;
  String get email;
  String? get rawPhone;
  int get vpoints;
  UserRole get role;
  DateTime get joinedAt;
  bool get active;
  UserLiteModel? get managedBy;
}

/// Base model class for UserModel.
@freezed
sealed class UserModel with _$UserModel implements BaseUserSchema, IUserModel {
  const UserModel._();

  /// Constructor for UserModel.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `enabled` (`users`)
  ///
  /// Fields:
  /// - String id : JsonKey('id')
  /// - String userId : JsonKey('user_id')
  /// - String? photo : JsonKey('photo')
  /// - String? rawFirstName : JsonKey('first_name')
  /// - String? rawLastName : JsonKey('last_name')
  /// - String email : JsonKey('email')
  /// - String? rawPhone : JsonKey('phone')
  /// - int vpoints : JsonKey('vpoints')
  /// - UserRole role : JsonKey('role')
  /// - DateTime joinedAt : JsonKey('joined_at')
  /// - bool active : JsonKey('active')
  /// - UserLiteModel? managedBy : JsonKey('managedBy')
  @TableModel(UserModel.tableName)
  @JsonSerializable(explicitToJson: true)
  const factory UserModel({
    @JsonKey(name: UserModel.idKey) required String id,
    @JsonKey(name: UserModel.userIdKey) required String userId,
    @JsonKey(name: UserModel.photoKey) required String? photo,
    @JsonKey(name: UserModel.rawFirstNameKey) required String? rawFirstName,
    @JsonKey(name: UserModel.rawLastNameKey) required String? rawLastName,
    @JsonKey(name: UserModel.emailKey) required String email,
    @JsonKey(name: UserModel.rawPhoneKey) required String? rawPhone,
    @JsonKey(name: UserModel.vpointsKey) required int vpoints,
    @JsonKey(name: UserModel.roleKey) required UserRole role,
    @JsonKey(name: UserModel.joinedAtKey) required DateTime joinedAt,
    @JsonKey(name: UserModel.activeKey) required bool active,
    @JoinedColumn(foreignKey: "managed_by_id", candidateKey: null)
    @JsonKey(name: UserModel.managedByKey)
    required UserLiteModel? managedBy,
  }) = _UserModel;

  /// Creates an instance of UserModel from a JSON map.
  factory UserModel.fromJson(Map<String, dynamic> json) =>
      _$UserModelFromJson(json);

  /// Supabase table configuration for this model.
  static const TableBuilder table = _tableUserModel;

  /// Table name: `users`
  static const String tableName = "users";

  /// Field name for id field with JsonKey('id')
  static const String idKey = "id";

  /// Field name for userId field with JsonKey('user_id')
  static const String userIdKey = "user_id";

  /// Field name for photo field with JsonKey('photo')
  static const String photoKey = "photo";

  /// Field name for rawFirstName field with JsonKey('first_name')
  static const String rawFirstNameKey = "first_name";

  /// Field name for rawLastName field with JsonKey('last_name')
  static const String rawLastNameKey = "last_name";

  /// Field name for email field with JsonKey('email')
  static const String emailKey = "email";

  /// Field name for rawPhone field with JsonKey('phone')
  static const String rawPhoneKey = "phone";

  /// Field name for vpoints field with JsonKey('vpoints')
  static const String vpointsKey = "vpoints";

  /// Field name for role field with JsonKey('role')
  static const String roleKey = "role";

  /// Field name for joinedAt field with JsonKey('joined_at')
  static const String joinedAtKey = "joined_at";

  /// Field name for active field with JsonKey('active')
  static const String activeKey = "active";

  /// Field name for managedBy field with JsonKey('managedBy')
  /// This is json key for joined field. with foreign key: managed_by_id and candidate key: null
  static const String managedByKey = "managedBy";
}

/// Represents the UserLiteModel model. generated by kimapp_generator
@freezed
sealed class UserLiteModel with _$UserLiteModel implements BaseUserSchema {
  const UserLiteModel._();

  /// Constructor for UserLiteModel.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `enabled`
  /// Table Name: `users`
  ///
  /// Fields:
  /// - String id : JsonKey('id')
  /// - String? photo : JsonKey('photo')
  /// - String? rawFirstName : JsonKey('first_name')
  /// - String? rawLastName : JsonKey('last_name')
  @TableModel(UserLiteModel.tableName)
  @JsonSerializable(explicitToJson: true)
  const factory UserLiteModel({
    @JsonKey(name: UserLiteModel.idKey) required String id,
    @JsonKey(name: UserLiteModel.photoKey) required String? photo,
    @JsonKey(name: UserLiteModel.rawFirstNameKey) required String? rawFirstName,
    @JsonKey(name: UserLiteModel.rawLastNameKey) required String? rawLastName,
  }) = _UserLiteModel;

  /// Creates an instance of UserLiteModel from a JSON map.
  factory UserLiteModel.fromJson(Map<String, dynamic> json) =>
      _$UserLiteModelFromJson(json);

  /// Supabase table configuration for this model.
  static const TableBuilder table = _tableUserLiteModel;

  /// Table name: `users`
  static const String tableName = "users";

  /// Field name for id field with JsonKey('id')
  static const String idKey = "id";

  /// Field name for photo field with JsonKey('photo')
  static const String photoKey = "photo";

  /// Field name for rawFirstName field with JsonKey('first_name')
  static const String rawFirstNameKey = "first_name";

  /// Field name for rawLastName field with JsonKey('last_name')
  static const String rawLastNameKey = "last_name";
}
