// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// KimappSchemaGenerator
// **************************************************************************

// ignore_for_file: invalid_annotation_target, unused_import, require_trailing_commas
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:kimapp/kimapp.dart';

import 'package:kfa_mobile_nu/exports.dart';
import 'user_model.dart';

part 'user_model.schema.freezed.dart';
part 'user_model.schema.g.dart';

/// Defines the table structure for User.
/// This class provides constant string values for table and column names,
/// facilitating type-safe database operations and query building.
class UserTable {
  const UserTable._();

  /// The name of the database table for User entities.
  /// Use this constant for constructing SQL queries to ensure consistency.
  static const String table = "users";

  /// Column: id
  /// Data type: `String`
  /// Key: `id`
  static const String id = "id";

  /// Column: user_id
  /// Data type: `String`
  /// Key: `user_id`
  static const String userId = "user_id";

  /// Column: photo
  /// Data type: `String?`
  /// Key: `photo`
  static const String photo = "photo";

  /// Column: first_name
  /// Data type: `String`
  /// Key: `first_name`
  static const String firstName = "first_name";

  /// Column: last_name
  /// Data type: `String`
  /// Key: `last_name`
  static const String lastName = "last_name";

  /// Column: email
  /// Data type: `String`
  /// Key: `email`
  static const String email = "email";

  /// Column: phone
  /// Data type: `String`
  /// Key: `phone`
  static const String phone = "phone";

  /// Column: vpoints
  /// Data type: `int`
  /// Key: `vpoints`
  static const String vpoints = "vpoints";

  /// Column: is_admin
  /// Data type: `bool`
  /// Key: `is_admin`
  static const String isAdmin = "is_admin";

  /// Column: joined_at
  /// Data type: `DateTime`
  /// Key: `joined_at`
  static const String joinedAt = "joined_at";
}

/// Base model class for UserModel.
@freezed
class UserModel with _$UserModel {
  const UserModel._();

  /// Constructor for UserModel.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `enabled` (`users`)
  ///
  /// Fields:
  /// - String id : JsonKey('id')
  /// - String userId : JsonKey('user_id')
  /// - String? photo : JsonKey('photo')
  /// - String firstName : JsonKey('first_name')
  /// - String lastName : JsonKey('last_name')
  /// - String email : JsonKey('email')
  /// - String phone : JsonKey('phone')
  /// - int vpoints : JsonKey('vpoints')
  /// - bool isAdmin : JsonKey('is_admin')
  /// - DateTime joinedAt : JsonKey('joined_at')
  @TableModel(UserModel.tableName)
  @JsonSerializable(explicitToJson: true)
  const factory UserModel({
    @JsonKey(name: UserModel.idKey) required String id,
    @JsonKey(name: UserModel.userIdKey) required String userId,
    @JsonKey(name: UserModel.photoKey) required String? photo,
    @JsonKey(name: UserModel.firstNameKey) required String firstName,
    @JsonKey(name: UserModel.lastNameKey) required String lastName,
    @JsonKey(name: UserModel.emailKey) required String email,
    @JsonKey(name: UserModel.phoneKey) required String phone,
    @JsonKey(name: UserModel.vpointsKey) required int vpoints,
    @JsonKey(name: UserModel.isAdminKey) required bool isAdmin,
    @JsonKey(name: UserModel.joinedAtKey) required DateTime joinedAt,
  }) = _UserModel;

  /// Creates an instance of UserModel from a JSON map.
  factory UserModel.fromJson(Map<String, dynamic> json) =>
      _$UserModelFromJson(json);

  /// Supabase table configuration for this model.
  static const TableBuilder table = _tableUserModel;

  /// Table name: `users`
  static const String tableName = "users";

  /// Field name for id field with JsonKey('id')
  static const String idKey = "id";

  /// Field name for userId field with JsonKey('user_id')
  static const String userIdKey = "user_id";

  /// Field name for photo field with JsonKey('photo')
  static const String photoKey = "photo";

  /// Field name for firstName field with JsonKey('first_name')
  static const String firstNameKey = "first_name";

  /// Field name for lastName field with JsonKey('last_name')
  static const String lastNameKey = "last_name";

  /// Field name for email field with JsonKey('email')
  static const String emailKey = "email";

  /// Field name for phone field with JsonKey('phone')
  static const String phoneKey = "phone";

  /// Field name for vpoints field with JsonKey('vpoints')
  static const String vpointsKey = "vpoints";

  /// Field name for isAdmin field with JsonKey('is_admin')
  static const String isAdminKey = "is_admin";

  /// Field name for joinedAt field with JsonKey('joined_at')
  static const String joinedAtKey = "joined_at";
}

/// Represents the UserLiteModel model. generated by kimapp_generator
@freezed
class UserLiteModel with _$UserLiteModel {
  const UserLiteModel._();

  /// Constructor for UserLiteModel.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `disabled`
  ///
  /// Fields:
  /// - String id : JsonKey('id')
  /// - String? photo : JsonKey('photo')
  /// - String firstName : JsonKey('first_name')
  /// - String lastName : JsonKey('last_name')
  @JsonSerializable(explicitToJson: true)
  const factory UserLiteModel({
    @JsonKey(name: UserLiteModel.idKey) required String id,
    @JsonKey(name: UserLiteModel.photoKey) required String? photo,
    @JsonKey(name: UserLiteModel.firstNameKey) required String firstName,
    @JsonKey(name: UserLiteModel.lastNameKey) required String lastName,
  }) = _UserLiteModel;

  /// Creates an instance of UserLiteModel from a JSON map.
  factory UserLiteModel.fromJson(Map<String, dynamic> json) =>
      _$UserLiteModelFromJson(json);

  /// Field name for id field with JsonKey('id')
  static const String idKey = "id";

  /// Field name for photo field with JsonKey('photo')
  static const String photoKey = "photo";

  /// Field name for firstName field with JsonKey('first_name')
  static const String firstNameKey = "first_name";

  /// Field name for lastName field with JsonKey('last_name')
  static const String lastNameKey = "last_name";
}
