// dart format width=80
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// KimappSchemaGenerator
// **************************************************************************

// ignore_for_file: invalid_annotation_target, unused_import, require_trailing_commas
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:kimapp/kimapp.dart';

import 'v_point_transaction_model.dart';

part 'v_point_transaction_model.schema.freezed.dart';
part 'v_point_transaction_model.schema.g.dart';

/// Defines the table structure for VPointTransaction.
/// This class provides constant string values for table and column names,
/// facilitating type-safe database operations and query building.
class VPointTransactionTable {
  const VPointTransactionTable._();

  /// The name of the database table for VPointTransaction entities.
  /// Use this constant for constructing SQL queries to ensure consistency.
  static const String table = "v_point_transactions";

  /// Column: id
  /// Data type: `int`
  /// Key: `id`
  static const String id = "id";

  /// Column: transaction_id
  /// Data type: `String`
  /// Key: `transaction_id`
  static const String transactionId = "transaction_id";

  /// Column: type
  /// Data type: `String`
  /// Key: `type`
  static const String type = "type";

  /// Column: user_id
  /// Data type: `String`
  /// Key: `user_id`
  static const String userId = "user_id";

  /// Column: vpoints
  /// Data type: `int`
  /// Key: `vpoints`
  static const String vpoints = "vpoints";

  /// Column: created_at
  /// Data type: `DateTime`
  /// Key: `created_at`
  static const String createdAt = "created_at";
}

/// Base class of this schema, this is the parent of all generated models in this schema
abstract class BaseVPointTransactionSchema {}

/// Base model class for this schema, this includes all properties of the base model, and get inherited by all generated models in this schema where [inheritAllFromBase()] is called and without any excepted fields.
abstract class IVPointTransactionModel {
  int get id;
  String get transactionId;
  String get type;
  String get userId;
  int get vpoints;
  DateTime get createdAt;
}

/// Base model class for VPointTransactionModel.
@freezed
sealed class VPointTransactionModel
    with _$VPointTransactionModel
    implements BaseVPointTransactionSchema, IVPointTransactionModel {
  const VPointTransactionModel._();

  /// Constructor for VPointTransactionModel.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `enabled` (`v_point_transactions`)
  ///
  /// Fields:
  /// - int id : JsonKey('id')
  /// - String transactionId : JsonKey('transaction_id')
  /// - String type : JsonKey('type')
  /// - String userId : JsonKey('user_id')
  /// - int vpoints : JsonKey('vpoints')
  /// - DateTime createdAt : JsonKey('created_at')
  @TableModel(VPointTransactionModel.tableName)
  @JsonSerializable(explicitToJson: true)
  const factory VPointTransactionModel({
    @JsonKey(name: VPointTransactionModel.idKey) required int id,
    @JsonKey(name: VPointTransactionModel.transactionIdKey)
    required String transactionId,
    @JsonKey(name: VPointTransactionModel.typeKey) required String type,
    @JsonKey(name: VPointTransactionModel.userIdKey) required String userId,
    @JsonKey(name: VPointTransactionModel.vpointsKey) required int vpoints,
    @JsonKey(name: VPointTransactionModel.createdAtKey)
    required DateTime createdAt,
  }) = _VPointTransactionModel;

  /// Creates an instance of VPointTransactionModel from a JSON map.
  factory VPointTransactionModel.fromJson(Map<String, dynamic> json) =>
      _$VPointTransactionModelFromJson(json);

  /// Supabase table configuration for this model.
  static const TableBuilder table = _tableVPointTransactionModel;

  /// Table name: `v_point_transactions`
  static const String tableName = "v_point_transactions";

  /// Field name for id field with JsonKey('id')
  static const String idKey = "id";

  /// Field name for transactionId field with JsonKey('transaction_id')
  static const String transactionIdKey = "transaction_id";

  /// Field name for type field with JsonKey('type')
  static const String typeKey = "type";

  /// Field name for userId field with JsonKey('user_id')
  static const String userIdKey = "user_id";

  /// Field name for vpoints field with JsonKey('vpoints')
  static const String vpointsKey = "vpoints";

  /// Field name for createdAt field with JsonKey('created_at')
  static const String createdAtKey = "created_at";
}
