// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ-kc_-FOjgybZcUdblGBgl72WTNbCfO0',
    appId: '1:739352974848:web:e21d546e0666a18604aae5',
    messagingSenderId: '739352974848',
    projectId: 'kfa-mobile-942f0',
    authDomain: 'kfa-mobile-942f0.firebaseapp.com',
    storageBucket: 'kfa-mobile-942f0.appspot.com',
    measurementId: 'G-C93Z298LV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9oyCc9P4l9u1FhPGd6FwAk-nBGSFJ9t0',
    appId: '1:739352974848:android:51ef161f6ed2686f04aae5',
    messagingSenderId: '739352974848',
    projectId: 'kfa-mobile-942f0',
    storageBucket: 'kfa-mobile-942f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXw2tsNJVqnzX6yI-sNnLBG8IBvpf3vd8',
    appId: '1:739352974848:ios:df2dc2c0890114e704aae5',
    messagingSenderId: '739352974848',
    projectId: 'kfa-mobile-942f0',
    storageBucket: 'kfa-mobile-942f0.appspot.com',
    iosBundleId: 'com.example.kfaMobileNu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXw2tsNJVqnzX6yI-sNnLBG8IBvpf3vd8',
    appId: '1:739352974848:ios:df2dc2c0890114e704aae5',
    messagingSenderId: '739352974848',
    projectId: 'kfa-mobile-942f0',
    storageBucket: 'kfa-mobile-942f0.appspot.com',
    iosBundleId: 'com.example.kfaMobileNu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ-kc_-FOjgybZcUdblGBgl72WTNbCfO0',
    appId: '1:739352974848:web:69c9dbbe47ee793204aae5',
    messagingSenderId: '739352974848',
    projectId: 'kfa-mobile-942f0',
    authDomain: 'kfa-mobile-942f0.firebaseapp.com',
    storageBucket: 'kfa-mobile-942f0.appspot.com',
    measurementId: 'G-30NDKE7NTH',
  );
}
